import { PetParent } from "@/types/pet-parents";

export const mockPetParents: PetParent[] = [
  {
    id: "1",
    firstName: "Jennifer",
    lastName: "Martinez",
    email: "jennifer.martinez@email.com",
    phone: "+1 (555) 123-4567",
    profileImage:
      "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=400",
    address: {
      street: "123 Oak Street",
      city: "New York",
      state: "NY",
      zipCode: "10001",
    },
    emergencyContact: {
      name: "Carlos Martinez",
      phone: "+1 (555) 987-6543",
      relationship: "Spouse",
    },
    pets: [
      {
        id: "p1",
        name: "Luna",
        species: "Dog",
        breed: "Golden Retriever",
        age: 3,
        gender: "female",
        weight: 28.5,
        color: "Golden",
        microchipId: "MC123456789",
        profileImage:
          "https://images.pexels.com/photos/1805164/pexels-photo-1805164.jpeg?auto=compress&cs=tinysrgb&w=400",
        medicalHistory: {
          vaccinations: ["Rabies", "DHPP", "Bordetella"],
          allergies: ["Chicken"],
          medications: ["Flea prevention"],
          lastVisit: "2024-01-15",
        },
        status: "healthy",
      },
      {
        id: "p2",
        name: "Whiskers",
        species: "Cat",
        breed: "Persian",
        age: 5,
        gender: "male",
        weight: 4.2,
        color: "White",
        microchipId: "MC987654321",
        profileImage:
          "https://images.pexels.com/photos/45201/kitty-cat-kitten-pet-45201.jpeg?auto=compress&cs=tinysrgb&w=400",
        medicalHistory: {
          vaccinations: ["FVRCP", "Rabies"],
          allergies: [],
          medications: ["Hairball control"],
          lastVisit: "2024-01-10",
        },
        status: "treatment",
      },
    ],
    registrationDate: "2021-03-15",
    totalVisits: 24,
    totalSpent: 2847.5,
    status: "active",
    preferredDoctor: "Dr. Sarah Johnson",
    notes: "Very caring pet parent. Always follows medical advice.",
    paymentMethod: "card",
  },
  {
    id: "2",
    firstName: "David",
    lastName: "Chen",
    email: "david.chen@email.com",
    phone: "+1 (555) 234-5678",
    profileImage:
      "https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=400",
    address: {
      street: "456 Pine Avenue",
      city: "Los Angeles",
      state: "CA",
      zipCode: "90210",
    },
    emergencyContact: {
      name: "Lisa Chen",
      phone: "+1 (555) 876-5432",
      relationship: "Sister",
    },
    pets: [
      {
        id: "p3",
        name: "Rocky",
        species: "Dog",
        breed: "German Shepherd",
        age: 7,
        gender: "male",
        weight: 35.8,
        color: "Black & Tan",
        microchipId: "MC456789123",
        profileImage:
          "https://images.pexels.com/photos/1490908/pexels-photo-1490908.jpeg?auto=compress&cs=tinysrgb&w=400",
        medicalHistory: {
          vaccinations: ["Rabies", "DHPP", "Lyme"],
          allergies: ["Beef"],
          medications: ["Joint supplement", "Pain management"],
          lastVisit: "2024-01-20",
        },
        status: "treatment",
      },
    ],
    registrationDate: "2019-07-22",
    totalVisits: 42,
    totalSpent: 5234.75,
    status: "active",
    preferredDoctor: "Dr. Michael Chen",
    notes: "Senior dog requires regular check-ups. Owner is very attentive.",
    paymentMethod: "insurance",
  },
  {
    id: "3",
    firstName: "Sarah",
    lastName: "Williams",
    email: "sarah.williams@email.com",
    phone: "+1 (555) 345-6789",
    profileImage:
      "https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=400",
    address: {
      street: "789 Elm Road",
      city: "Chicago",
      state: "IL",
      zipCode: "60601",
    },
    emergencyContact: {
      name: "Michael Williams",
      phone: "+1 (555) 765-4321",
      relationship: "Husband",
    },
    pets: [
      {
        id: "p4",
        name: "Bella",
        species: "Cat",
        breed: "Maine Coon",
        age: 2,
        gender: "female",
        weight: 5.8,
        color: "Tabby",
        microchipId: "MC789123456",
        profileImage:
          "https://images.pexels.com/photos/416160/pexels-photo-416160.jpeg?auto=compress&cs=tinysrgb&w=400",
        medicalHistory: {
          vaccinations: ["FVRCP", "Rabies", "FeLV"],
          allergies: ["Fish"],
          medications: [],
          lastVisit: "2024-01-08",
        },
        status: "healthy",
      },
      {
        id: "p5",
        name: "Charlie",
        species: "Rabbit",
        breed: "Holland Lop",
        age: 1,
        gender: "male",
        weight: 1.2,
        color: "Brown",
        profileImage:
          "https://images.pexels.com/photos/326012/pexels-photo-326012.jpeg?auto=compress&cs=tinysrgb&w=400",
        medicalHistory: {
          vaccinations: ["RHDV"],
          allergies: [],
          medications: [],
          lastVisit: "2024-01-12",
        },
        status: "healthy",
      },
    ],
    registrationDate: "2022-11-08",
    totalVisits: 8,
    totalSpent: 1245.25,
    status: "active",
    preferredDoctor: "Dr. Emily Rodriguez",
    notes: "New pet parent, very enthusiastic about pet care.",
    paymentMethod: "card",
  },
  {
    id: "4",
    firstName: "Robert",
    lastName: "Johnson",
    email: "robert.johnson@email.com",
    phone: "+1 (555) 456-7890",
    profileImage:
      "https://images.pexels.com/photos/1043471/pexels-photo-1043471.jpeg?auto=compress&cs=tinysrgb&w=400",
    address: {
      street: "321 Maple Drive",
      city: "Austin",
      state: "TX",
      zipCode: "73301",
    },
    emergencyContact: {
      name: "Emma Johnson",
      phone: "+1 (555) 654-3210",
      relationship: "Daughter",
    },
    pets: [
      {
        id: "p6",
        name: "Max",
        species: "Dog",
        breed: "Labrador Mix",
        age: 8,
        gender: "male",
        weight: 32.1,
        color: "Chocolate",
        microchipId: "MC321654987",
        profileImage:
          "https://images.pexels.com/photos/1851164/pexels-photo-1851164.jpeg?auto=compress&cs=tinysrgb&w=400",
        medicalHistory: {
          vaccinations: ["Rabies", "DHPP"],
          allergies: ["Corn"],
          medications: ["Arthritis medication"],
          lastVisit: "2024-01-18",
        },
        status: "treatment",
      },
    ],
    registrationDate: "2018-05-14",
    totalVisits: 56,
    totalSpent: 7892.4,
    status: "active",
    preferredDoctor: "Dr. James Thompson",
    notes: "Long-time client. Senior dog with ongoing health management.",
    paymentMethod: "cash",
  },
  {
    id: "5",
    firstName: "Amanda",
    lastName: "Davis",
    email: "amanda.davis@email.com",
    phone: "+1 (555) 567-8901",
    profileImage:
      "https://images.pexels.com/photos/1130626/pexels-photo-1130626.jpeg?auto=compress&cs=tinysrgb&w=400",
    address: {
      street: "654 Cedar Lane",
      city: "Seattle",
      state: "WA",
      zipCode: "98101",
    },
    emergencyContact: {
      name: "James Davis",
      phone: "+1 (555) 543-2109",
      relationship: "Brother",
    },
    pets: [
      {
        id: "p7",
        name: "Milo",
        species: "Cat",
        breed: "Siamese",
        age: 4,
        gender: "male",
        weight: 4.8,
        color: "Seal Point",
        microchipId: "MC654987321",
        profileImage:
          "https://images.pexels.com/photos/1170986/pexels-photo-1170986.jpeg?auto=compress&cs=tinysrgb&w=400",
        medicalHistory: {
          vaccinations: ["FVRCP", "Rabies"],
          allergies: ["Dairy"],
          medications: ["Dental care"],
          lastVisit: "2024-01-05",
        },
        status: "healthy",
      },
    ],
    registrationDate: "2020-09-30",
    totalVisits: 18,
    totalSpent: 2156.8,
    status: "inactive",
    preferredDoctor: "Dr. Lisa Park",
    notes: "Moved recently, considering transfer to another clinic.",
    paymentMethod: "card",
  },
];
