import { Doctor } from "@/types/doctor";

export const mockDoctors: Doctor[] = [
  {
    id: "1",
    name: "Dr. Sarah Johnson",
    email: "sarah.johnson@vetcare.com",
    phone: "+1 (555) 123-4567",
    specialization: "Small Animal Medicine",
    qualification: "DVM, PhD",
    experience: 8,
    licenseNumber: "VET12345",
    profileImage:
      "https://images.pexels.com/photos/5452201/pexels-photo-5452201.jpeg?auto=compress&cs=tinysrgb&w=400",
    status: "active",
    rating: 4.8,
    totalPatients: 1247,
    joinedDate: "2020-03-15",
    address: {
      street: "123 Main Street",
      city: "New York",
      state: "NY",
      zipCode: "10001",
    },
    schedule: [
      {
        day: "Monday",
        startTime: "09:00",
        endTime: "17:00",
        isAvailable: true,
      },
      {
        day: "Tuesday",
        startTime: "09:00",
        endTime: "17:00",
        isAvailable: true,
      },
      {
        day: "Wednesday",
        startTime: "09:00",
        endTime: "17:00",
        isAvailable: true,
      },
      {
        day: "Thursday",
        startTime: "09:00",
        endTime: "17:00",
        isAvailable: true,
      },
      {
        day: "Friday",
        startTime: "09:00",
        endTime: "15:00",
        isAvailable: true,
      },
      {
        day: "Saturday",
        startTime: "10:00",
        endTime: "14:00",
        isAvailable: true,
      },
      { day: "Sunday", startTime: "", endTime: "", isAvailable: false },
    ],
    fees: {
      consultation: 75,
      followUp: 45,
    },
    chamber: {
      name: "City Veterinary Clinic",
      address: "456 Oak Avenue, New York, NY 10002",
      phone: "+1 (555) 987-6543",
    },
  },
  {
    id: "2",
    name: "Dr. Michael Chen",
    email: "michael.chen@vetcare.com",
    phone: "+1 (555) 234-5678",
    specialization: "Exotic Animal Medicine",
    qualification: "DVM, MS",
    experience: 12,
    licenseNumber: "VET23456",
    profileImage:
      "https://images.pexels.com/photos/6129967/pexels-photo-6129967.jpeg?auto=compress&cs=tinysrgb&w=400",
    status: "active",
    rating: 4.9,
    totalPatients: 856,
    joinedDate: "2018-07-22",
    address: {
      street: "789 Pine Road",
      city: "Los Angeles",
      state: "CA",
      zipCode: "90210",
    },
    schedule: [
      {
        day: "Monday",
        startTime: "10:00",
        endTime: "18:00",
        isAvailable: true,
      },
      {
        day: "Tuesday",
        startTime: "10:00",
        endTime: "18:00",
        isAvailable: true,
      },
      {
        day: "Wednesday",
        startTime: "10:00",
        endTime: "18:00",
        isAvailable: true,
      },
      {
        day: "Thursday",
        startTime: "10:00",
        endTime: "18:00",
        isAvailable: true,
      },
      {
        day: "Friday",
        startTime: "10:00",
        endTime: "16:00",
        isAvailable: true,
      },
      { day: "Saturday", startTime: "", endTime: "", isAvailable: false },
      { day: "Sunday", startTime: "", endTime: "", isAvailable: false },
    ],
    fees: {
      consultation: 95,
      followUp: 55,
    },
    chamber: {
      name: "Exotic Pet Care Center",
      address: "321 Sunset Blvd, Los Angeles, CA 90028",
      phone: "+1 (555) 876-5432",
    },
  },
  {
    id: "3",
    name: "Dr. Emily Rodriguez",
    email: "emily.rodriguez@vetcare.com",
    phone: "+1 (555) 345-6789",
    specialization: "Surgery & Emergency Care",
    qualification: "DVM, DACVS",
    experience: 15,
    licenseNumber: "VET34567",
    profileImage:
      "https://images.pexels.com/photos/5452293/pexels-photo-5452293.jpeg?auto=compress&cs=tinysrgb&w=400",
    status: "active",
    rating: 4.7,
    totalPatients: 2134,
    joinedDate: "2016-01-10",
    address: {
      street: "567 Elm Street",
      city: "Chicago",
      state: "IL",
      zipCode: "60601",
    },
    schedule: [
      {
        day: "Monday",
        startTime: "08:00",
        endTime: "20:00",
        isAvailable: true,
      },
      {
        day: "Tuesday",
        startTime: "08:00",
        endTime: "20:00",
        isAvailable: true,
      },
      {
        day: "Wednesday",
        startTime: "08:00",
        endTime: "20:00",
        isAvailable: true,
      },
      {
        day: "Thursday",
        startTime: "08:00",
        endTime: "20:00",
        isAvailable: true,
      },
      {
        day: "Friday",
        startTime: "08:00",
        endTime: "18:00",
        isAvailable: true,
      },
      {
        day: "Saturday",
        startTime: "09:00",
        endTime: "15:00",
        isAvailable: true,
      },
      {
        day: "Sunday",
        startTime: "09:00",
        endTime: "15:00",
        isAvailable: true,
      },
    ],
    fees: {
      consultation: 120,
      followUp: 70,
    },
    chamber: {
      name: "Emergency Veterinary Hospital",
      address: "890 Medical Center Dr, Chicago, IL 60611",
      phone: "+1 (555) 765-4321",
    },
  },
  {
    id: "4",
    name: "Dr. James Thompson",
    email: "james.thompson@vetcare.com",
    phone: "+1 (555) 456-7890",
    specialization: "Large Animal Medicine",
    qualification: "DVM",
    experience: 6,
    licenseNumber: "VET45678",
    profileImage:
      "https://images.pexels.com/photos/5452274/pexels-photo-5452274.jpeg?auto=compress&cs=tinysrgb&w=400",
    status: "pending",
    rating: 4.5,
    totalPatients: 432,
    joinedDate: "2022-09-05",
    address: {
      street: "234 Country Lane",
      city: "Austin",
      state: "TX",
      zipCode: "73301",
    },
    schedule: [
      {
        day: "Monday",
        startTime: "07:00",
        endTime: "19:00",
        isAvailable: true,
      },
      {
        day: "Tuesday",
        startTime: "07:00",
        endTime: "19:00",
        isAvailable: true,
      },
      {
        day: "Wednesday",
        startTime: "07:00",
        endTime: "19:00",
        isAvailable: true,
      },
      {
        day: "Thursday",
        startTime: "07:00",
        endTime: "19:00",
        isAvailable: true,
      },
      {
        day: "Friday",
        startTime: "07:00",
        endTime: "17:00",
        isAvailable: true,
      },
      {
        day: "Saturday",
        startTime: "08:00",
        endTime: "16:00",
        isAvailable: true,
      },
      { day: "Sunday", startTime: "", endTime: "", isAvailable: false },
    ],
    fees: {
      consultation: 85,
      followUp: 50,
    },
    chamber: {
      name: "Rural Veterinary Services",
      address: "456 Ranch Road, Austin, TX 73302",
      phone: "+1 (555) 654-3210",
    },
  },
  {
    id: "5",
    name: "Dr. Lisa Park",
    email: "lisa.park@vetcare.com",
    phone: "+1 (555) 567-8901",
    specialization: "Dermatology",
    qualification: "DVM, DACVD",
    experience: 10,
    licenseNumber: "VET56789",
    profileImage:
      "https://images.pexels.com/photos/5452254/pexels-photo-5452254.jpeg?auto=compress&cs=tinysrgb&w=400",
    status: "suspended",
    rating: 4.6,
    totalPatients: 923,
    joinedDate: "2019-11-18",
    address: {
      street: "678 Maple Avenue",
      city: "Seattle",
      state: "WA",
      zipCode: "98101",
    },
    schedule: [
      {
        day: "Monday",
        startTime: "09:00",
        endTime: "17:00",
        isAvailable: false,
      },
      {
        day: "Tuesday",
        startTime: "09:00",
        endTime: "17:00",
        isAvailable: false,
      },
      {
        day: "Wednesday",
        startTime: "09:00",
        endTime: "17:00",
        isAvailable: false,
      },
      {
        day: "Thursday",
        startTime: "09:00",
        endTime: "17:00",
        isAvailable: false,
      },
      {
        day: "Friday",
        startTime: "09:00",
        endTime: "17:00",
        isAvailable: false,
      },
      { day: "Saturday", startTime: "", endTime: "", isAvailable: false },
      { day: "Sunday", startTime: "", endTime: "", isAvailable: false },
    ],
    fees: {
      consultation: 100,
      followUp: 60,
    },
    chamber: {
      name: "Specialized Pet Dermatology",
      address: "123 Health Plaza, Seattle, WA 98102",
      phone: "+1 (555) 543-2109",
    },
  },
];
